title:              Yoons'TIL_Blog
email:              yoonrock02@gmail.com
description:        coding_knowledge_repository
author:             yoons
baseurl:            ""
url:                "https://yoonseok0323.github.io"

# Social Profiles
twitter_username:   
github_username:    yoonseok0323
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
