title:              Yoons'TIL_Blog
email:              yoonrock02@gmail.com
description:        coding_knowledge_repository
author:             yoons
baseurl:            ""
url:                "https://yoonseok0323.github.io"


# Site Settings
locale                   : "en-US"
title                    : "Yoons'TIL_Blog"
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Yoon"
description              : "coding_knowlege_repository."
url                      : "https://syh39.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : 
teaser                   : 
logo                     : 
masthead_title           : 

# breadcrumbs            : false # true, false (default)
words_per_minute         : 200
comments:
  provider               : 
    disqus:
    shortname            :
    discourse:
    server               : 
  facebook:
   
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : 
    issue_term           : # "pathname" (default)
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:

# Social Profiles
twitter_username:   
github_username:    yoonseok0323
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
